version: '3.9'

services:
  coworking-db:
    image: postgres:latest
    container_name: coworking
    environment:
      POSTGRES_DB: coworking
      POSTGRES_USER: coworking
      POSTGRES_PASSWORD: coworking
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:


