version: '3.8'

services:
  coworking-db:
    image: postgres:latest
    container_name: coworking-db
    environment:
      POSTGRES_DB: coworking
      POSTGRES_USER: usver
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  postgres-data:
